version: '3'
services: 
    app:
        container_name: structure
        restart: unless-stopped
        env_file: .env
        environment: 
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
            - MONGO_HOSTNAME=mongo
        build: .
        ports: 
            - "4000:4000"
        networks: 
            - app-net
    mongo:
        container_name: mongo
        image: mongo:4.2.6-bionic
        restart: unless-stopped
        volumes: 
            - "~/mongo-db-volum:/data/db"
        networks: 
            - app-net
networks: 
    app-net:
        driver: bridge